#!/usr/bin/env python

### MG 2/6/2020 - original idea from fastai dl2 course stripped to bare minimum

# import json,fire,re
import json
from pathlib import Path
import io

def is_export(cell):
    if cell['cell_type'] != 'code': return False
    src = cell['source']
    if len(src) == 0 or len(src[0]) < 7: return False
    return '#export' in src[0]

       
def nb2script(fname):
    "Finds cells starting with `#export` and puts them into a new module"
    fname = Path(f'{fname}.ipynb')
    fname_out = f'exp_{fname.stem.split("_")[0].lower()}.py'
    main_dic = json.load(open(fname,'r',encoding="utf-8"))
    code_cells = [c for c in main_dic['cells'] if is_export(c)]
    module = f'''
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: {fname.name}

'''
    for cell in code_cells: module += ''.join(cell['source'][1:]) + '\n\n'
    output_path = fname_out
    with io.open(output_path, "w", encoding="utf-8") as f:
        f.write(module[:-2])
    print(f"Converted {fname} to {output_path}")

